name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  dockerCI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SourceRepo
        uses: actions/checkout@v4
        with:
          repository: SebTarLP/SourceRepo

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            kosier/task2:latest
            kosier/task2:${{ inputs.tag }}
            
  kubernetesCI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ConfigRepo
        uses: actions/checkout@v4
        with:
          repository: SebTarLP/ConfigRepo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.email "sebastian.tarasiuk@linuxpolska.pl"
          git config user.name "sebtarlp"

      - name: Update Manifest
        run: |
          sed -i "s/task2:*/task2:${{ inputs.tag }}/g" deployment.yaml

      - name: Commit and Push
        run: |
          git add .
          git commit -m "Update"
          git push
      
          

    

      
  
